[build-options]
observabilityIncluded = true
#offline = true
#skipTests = false
#cloud = "k8s"
#taintCheck = true

#[[platform.libraries]]
#artifactId = "mysql-connector-java"
#version = "5.1.45"
#path = "./libs/mysql-connector-java-5.1.45.jar"
#groupId = "mysql"
