[package]
org = "ballerina"
name = "lang.test"
version = "1.0.0"

[[platform.java11.dependency]]
<<<<<<< HEAD
path = "../libs/ballerina-lang-test-2.0.0-alpha3-SNAPSHOT.jar"
=======
path = "../libs/ballerina-lang-test-2.0.0-alpha3-SNAPSHOT.jar"
>>>>>>> e002057ae4c28c1c09247ec619ca4bb8c451d5e0
groupId = "ballerina"
artifactId = "io"
version = "0.5.0"
