[package]
org = "ballerina"
name = "test"
version = "0.0.0"

[[platform.java11.dependency]]
<<<<<<< HEAD
path = "../libs/testerina-core-2.0.0-alpha3-SNAPSHOT.jar"
=======
path = "../libs/testerina-core-2.0.0-alpha3-SNAPSHOT.jar"
>>>>>>> e002057ae4c28c1c09247ec619ca4bb8c451d5e0
groupId = "ballerina"
artifactId = "mock"
version = "0.0.0"


[[platform.java11.dependency]]
path = "../libs/java-diff-utils-4.5.jar"
groupId = "io.github.java-diff-utils"
artifactId = "java-diff-utils"
version = "4.5.0"
