[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "io"
    version = "0.5.0"
    path = "<PATH>/ballerina-io-<VERSION>.jar"
    groupId = "ballerina"
    modules = ["io"]
