name: Publish Ballerina Snapshot

on:
    repository_dispatch:
        types: [stdlib-module-push, ballerina-lang-push]
    workflow_dispatch:

jobs:
    publish-stdlib-modules:
        name: Publish Standard Library Modules
        runs-on: ubuntu-latest
        if: github.repository_owner == 'ThisaruGuruge'
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Trigger the Standard Library Module Builds
                uses: ballerina-platform/ballerina-action@master
                with:
                    args:
                        run publish
                env:
                    WORKING_DIR: ./stdlib/release
                    GITHUB_TOKEN: ${{ secrets.BAL_BOT_PAT }}
                    EVENT_TYPE: ${{ github.event.action }}
